### ISSUE TITLE
Support of global PATH defines

### ISSUE THREAD

**Issue by popstas** [viasite-ansible/ansible-role-zsh#14]
For example, if I installed npm, I want to expose global packages to all users.

**Comment by tnaglo** [comment]
WSL2 under Windows prepends the Windows PATH to the $PATH variable.
I had to comment out the line in `~/.zshrc` that sets the PATH

would it be wrong to only extend the existing PATH instead of replacing it

here: `templates/zshrc.j2`: 
```export PATH="{{ zsh_path | join(":") }}"```

or here:
`defaults/main.yml`
```zsh_path:
  - "{{ zsh_fzf_path }}"
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
```

**Comment by popstas** [comment]
@tnaglo, agreed, I added extending of `PATH`:

```
export PATH="$PATH:{{ zsh_path | join(":") }}"
```

Something of paths may duplicate, but it should work :)
