### ISSUE TITLE
insecure directories and files

### ISSUE THREAD

**Issue by xxdvxx** [viasite-ansible/ansible-role-zsh#26]
~  sudo -s                                                                                          ✘  23:16:19 
zsh compinit: insecure directories and files, run compaudit for list.                                                
Ignore insecure directories and files and continue [y] or abort compinit [n]?

 ~  compaudit                                                                                        ✘  23:16:10 
There are insecure directories and files:
/home/jss/.antigen/bundles/ytet5uy4/fzf-widgets/autoload/libexec
/home/jss/.antigen/bundles/ytet5uy4/fzf-widgets/autoload/widgets
/home/jss/.antigen/bundles/robbyrussell/oh-my-zsh/lib
/home/jss/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/command-not-found
/home/jss/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/fancy-ctrl-z
/home/jss/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git-extras
/home/jss/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/gnu-utils
/home/jss/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/rake
/home/jss/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/systemd
/home/jss/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/python
/home/jss/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/vagrant
/home/jss/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/zsh_reload
/home/jss/.antigen/bundles/zsh-users/zsh-autosuggestions
/home/jss/.antigen/bundles/popstas/zsh-command-time
/home/jss/.antigen/bundles/unixorn/autoupdate-antigen.zshplugin
/home/jss/.antigen/bundles/urbainvaes/fzf-marks
/home/jss/.antigen/bundles/ytet5uy4/fzf-widgets
/home/jss/.antigen/bundles/zdharma/fast-syntax-highlighting
/home/jss/.antigen/bundles/ytet5uy4/fzf-widgets/autoload
/home/jss/.antigen/bundles/ytet5uy4/fzf-widgets/autoload
/home/jss/.antigen/bundles/robbyrussell/oh-my-zsh
/home/jss/.antigen/bundles/robbyrussell/oh-my-zsh/plugins
/home/jss/.antigen/bundles/robbyrussell/oh-my-zsh/plugins
/home/jss/.antigen/bundles/robbyrussell/oh-my-zsh/plugins
/home/jss/.antigen/bundles/robbyrussell/oh-my-zsh/plugins
/home/jss/.antigen/bundles/robbyrussell/oh-my-zsh/plugins
/home/jss/.antigen/bundles/robbyrussell/oh-my-zsh/plugins
/home/jss/.antigen/bundles/robbyrussell/oh-my-zsh/plugins
/home/jss/.antigen/bundles/robbyrussell/oh-my-zsh/plugins
/home/jss/.antigen/bundles/robbyrussell/oh-my-zsh/plugins
/home/jss/.antigen/bundles/zsh-users
/home/jss/.antigen/bundles/popstas
/home/jss/.antigen/bundles/unixorn
/home/jss/.antigen/bundles/urbainvaes
/home/jss/.antigen/bundles/ytet5uy4
/home/jss/.antigen/bundles/zdharma
/home/jss/.antigen/bundles/ytet5uy4/fzf-widgets/autoload/libexec/__fzf::widget::check
/home/jss/.antigen/bundles/ytet5uy4/fzf-widgets/autoload/libexec/__fzf::widget::clear
/home/jss/.antigen/bundles/ytet5uy4/fzf-widgets/autoload/libexec/__fzf::widget::exec
/home/jss/.antigen/bundles/ytet5uy4/fzf-widgets/autoload/libexec/__fzf::widget::filter
/home/jss/.antigen/bundles/ytet5uy4/fzf-widgets/autoload/libexec/__fzf::widget::init
/home/jss/.antigen/bundles/ytet5uy4/fzf-widgets/autoload/libexec/__fzf::widget::insert
/home/jss/.antigen/bundles/ytet5uy4/fzf-widgets/autoload/libexec/__fzf::widget::print
/home/jss/.antigen/bundles/ytet5uy4/fzf-widgets/autoload/libexec/__fzf::widget::replace
/home/jss/.antigen/bundles/ytet5uy4/fzf-widgets/autoload/libexec/__fzf::widget::select
/home/jss/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/python/_python
/home/jss/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/vagrant/_vagrant

 ~  chmod -R 700 .antigen                                                                                23:21:08 

 ~  chown -R jss:jss .antigen                                                                            23:21:16 

 ~  ls -l /home/jss/.antigen/bundles                                                                     23:21:20 
итого 32
drwx------ 3 jss jss 4096 фев  4 01:36 bhilburn
drwx------ 3 jss jss 4096 фев  4 01:36 popstas
drwx------ 3 jss jss 4096 фев  4 01:36 robbyrussell
drwx------ 3 jss jss 4096 фев  4 01:36 unixorn
drwx------ 3 jss jss 4096 фев  4 01:36 urbainvaes
drwx------ 3 jss jss 4096 фев  4 01:36 ytet5uy4
drwx------ 3 jss jss 4096 фев  4 01:36 zdharma
drwx------ 3 jss jss 4096 фев  4 01:36 zsh-users

 ~  sudo -s                                                                                              23:21:23 
zsh compinit: insecure directories and files, run compaudit for list.                                                
Ignore insecure directories and files and continue [y] or abort compinit [n]?

**Comment by popstas** [comment]
@xxdvxx, I have no idea how to fix it. man zshcompsys reveals the following about the security check:

> For security reasons compinit also checks if the completion system would use files not owned by root or by the current user, or files in directories that are world- or group-writable or that are not owned by root or by the current user. If such files or directories are found, compinit will ask if the completion system should really be used. To avoid these tests and make all files found be used without asking, use the option -u, and to make compinit silently ignore all insecure files and directories use the option -i. This security check is skipped entirely when the -C option is given.
> 
> The security check can be retried at any time by running the function compaudit.

zsh tells that you are using completion files that owned not root, but jss.

Personally, I apply zsh role to root too and become root with `sudo -i`.

Also, when you are root and want to become user, you should use `su jss -` instead `su jss` to avoid some other warnings.

Is this answer satisfy you?
