### ISSUE TITLE
parameterized template file

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [viasite-ansible/ansible-role-zsh#28]
`zshrc.j2` is hard coded in `tasks/configure.yml`.

But I want to use my custom template to use as below for blockinfile.

```
# BEGIN MY CUSTOM FASD SETTING
# END MY CUSTOM FASD SETTING
```

Could I create a PR?

**Comment by popstas** [comment]
You can append your config to ~/.zshrc.local, without ansible.
If you need to replace something in zshrc.j2, then welcome to PR )

I'm also use similar variable in [other role](https://github.com/viasite-ansible/ansible-role-site/blob/master/tasks/user.yml#L39) for provision speedup and simple zsh environment.
