### ISSUE TITLE
Replace sudo with become and --ask-become-pass

### ISSUE THREAD

**Issue by NickVolynkin** [viasite-ansible/ansible-role-zsh#29]
This roles uses [`become`](https://docs.ansible.com/ansible/latest/user_guide/become.html#id1) to let ansible operate as a privileged user. This is the right and preferred way. But instead of asking for `become` password, the README recommends to run ansible with `sudo`:

``` bash
sudo ansible-playbook -i "localhost," -c local playbook.yml
```
This doesn't seem to be the right or required practice. For me it resulted in files in my `~/` owned by root a couple of times. Instead, we can tell ansible to ask for password with `--ask-become-pass` or `-K`:

```
ansible-playbook -i "localhost," -c local -K playbook.yml
```
Also, it seems that `ansible-galaxy` does not need `sudo` either:
```bash
sudo ansible-galaxy install viasite-ansible.zsh
```
If you agree, I will throw a pull-request myself.

**Comment by popstas** [comment]
Agreed

**Comment by popstas** [comment]
Late fix ) I'm used -b instead of -K, also removed sudo from ansible-galaxy.

After install check root owned files:
```
find ~ -user root
```

No root files after install on clean Ubuntu 20.20.
