### ISSUE TITLE
How can I disable a bundle?

### ISSUE THREAD

**Issue by codayblue** [viasite-ansible/ansible-role-zsh#30]
I want to disable the the auto suggestion bundle but from what I have found I appear to have to edit the .zshrc which says to not edit it and to use the .zshrc.local. I just wanted to check if there was a way I am not aware of or if I should make a PR to add functionality to be able to choose bundles you dont want?

**Comment by popstas** [comment]
You should copy `zsh_antigen_bundles` from `default.yml` to your playbook and remove autosuggestions from bundles list.

**Comment by codayblue** [comment]
That solved my issue thanks!
