### ISSUE TITLE
Fails when running in check mode

### ISSUE THREAD

**Issue by al-v-in** [viasite-ansible/ansible-role-zsh#31]
When running in check mode (`--check`) the playbook fails on several tasks (I think the ones that require data from registered variables?). I believe best practice is just to [ignore or not run](https://docs.ansible.com/ansible/latest/user_guide/playbooks_checkmode.html#information-about-check-mode-in-variables) those tasks when running check mode.

**Comment by popstas** [comment]
@al-v-in, thank you! Fixed, now role works correct in check mode.
