### ISSUE TITLE
Add Powerlevel10k theme

### ISSUE THREAD

**Issue by ghost** [viasite-ansible/ansible-role-zsh#32]
Hello,

Could you please add support for Powerlevel10k  theme
https://github.com/romkatv/powerlevel10k

**Comment by popstas** [comment]
@sunofsparda, you can just add this to your playbook:

``` yaml
zsh_antigen_theme: "romkatv/powerlevel10k powerlevel10k"
```

Just switched to powerlevel10k, it works.

**Comment by ghost** [comment]
Many thanks)
