### ISSUE TITLE
Hotkeys configure and hotkeys list

### ISSUE THREAD

**Issue by popstas** [viasite-ansible/ansible-role-zsh#4]
1. Need for way to define hotkeys for plugins and for zsh core.

2. Need for way to show hotkeys list to user.

**Comment by Philistino** [comment]
Hey thanks for maintaining this role! I have a quick question: is there a way to see which key presses I should use for the fzf hotkeys? 

For instance, in the case of '^@c', what keys do I need to press on my keyboard to use the fzf CD widget? Alt+c does not do anything, nor does Ctrl+@+c. I'm using zsh on a fresh Ubuntu server 22.04 install. 

I really appreciate the help!
