### ISSUE TITLE
TASK [viasite-ansible.zsh : Merge bundles lists]

### ISSUE THREAD

**Issue by m4rcw0lf** [viasite-ansible/ansible-role-zsh#41]
Hey.

After executing ./install.sh on debian stretch for manual install i got the following issue for the TASK [viasite-ansible.zsh : Merge bundles lists]:

> fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while templating '[{u'when': u\"{{ ansible_os_family != 'Darwin' }}\", u'name': u'command-not-found'}, {u'command': u'brew', u'name': u'brew'}, {u'command': u'docker', u'name': u'docker'}, {u'command': u'docker-compose', u'name': u'docker-compose'}, u'fancy-ctrl-z', u'git-extras', u'gnu-utils', {u'command': u'http', u'name': u'httpie'}, {u'command': u'go', u'name': u'go'}, {u'command': u'gulp', u'name': u'gulp'}, {u'command': u'pip', u'name': u'pip'}, {u'command': u'rake', u'name': u'rake'}, {u'command': u'symfony', u'name': u'symfony2'}, {u'command': u'systemctl', u'name': u'systemd'}, u'python', {u'command': u'tmux', u'name': u'tmux'}, {u'command': u'vagrant', u'name': u'vagrant'}, {u'command': u'drall', u'name': u'viasite/drall'}, {u'command': u'drs', u'name': u'viasite/drupal-scripts'}, {u'command': u'dbdump', u'name': u'viasite/server-scripts'}, {u'command': u'ansible-deploy', u'name': u'viasite-ansible/zsh-ansible-server'}, u'zsh_reload', {u'when': u\"{{ zsh_version | default(false) | version_compare('5.0', '>=') }}\", u'name': u'zsh-users/zsh-autosuggestions'}, u'popstas/zsh-command-time', {u'when': u'{{ zsh_update_interval > 0 }}', u'name': u'unixorn/autoupdate-antigen.zshplugin'}, u'urbainvaes/fzf-marks', u'{{ fzf_widgets }}', {u'when': u\"{{ zsh_version | default(false) | version_compare('4.3.17', '>=') }}\", u'name': u'zdharma/fast-syntax-highlighting@v1.2'}]'. Error was a <class 'ansible.errors.AnsibleError'>, original message: template error while templating string: no filter named 'version_compare'. String: {{ zsh_version | default(false) | version_compare('5.0', '>=') }}"}

Any ideas to fix it?

**Comment by ubmarco** [comment]
Ansible renamed `version_compare` to `version` in Ansible version 2.5 while keeping support for the old filter. I experienced the same issue after upgrading Ansible to 2.9. I guess support for `version_compare` was dropped in 2.9. It is also not a filter anymore but a test. Replacing `| version_compare(...)` with `is version(...)` fixes the issue for me locally.

Ah, I see there is already a PR for this: https://github.com/viasite-ansible/ansible-role-zsh/pull/42

**Comment by popstas** [comment]
#42 merged
