### ISSUE TITLE
How enable kubectl plugin?

### ISSUE THREAD

**Issue by Kamerads** [viasite-ansible/ansible-role-zsh#43]
How enable kubectl plugin?

**Comment by popstas** [comment]
You can add `kubectl` to `zsh_antigen_bundles` or `zsh_antigen_bundles_extras` - https://github.com/viasite-ansible/ansible-role-zsh#configure-bundles

**Comment by Kamerads** [comment]
what to write in .zshrc.local to connect .oh-my-zsh/plugins/kubectl?

**Comment by popstas** [comment]
I think that you cannot enable it with .zshrc.local, but you can try this:
```
antigen bundle kubectl
antigen apply
```
