### ISSUE TITLE
No zprofile?

### ISSUE THREAD

**Issue by SturmB** [viasite-ansible/ansible-role-zsh#45]
I have a situation where I'm also installing Ruby using [geerlingguy's role](https://galaxy.ansible.com/geerlingguy/ruby). This places a shell script in `/etc/profile.d/` called `rubygems.sh`. (There are several other `*.sh` files there, btw.)

Because zsh does not source `/etc/profile` (to the best of my knowledge), none of these scripts ever run. However, isn't zsh supposed to install `/etc/zprofile`? If so, this role does not do so. Thus, no scripts in `/etc/profile.d/` are ever sourced and, therefore, Ruby and some gems I install using geerlingguy's role are not accessible.

Am I wrong about any of this? Or what sort of fix needs to happen here?

**Comment by popstas** [comment]
You are right, `/etc/profile.d` should be sourced to shell.

As temporary solution: you can add to `~/.zshrc.local` (create it):
```
source /etc/profile.d/rubygems.sh
```

Or include all in `/etc/profile`:
```
source /etc/profile
```

I'm not sure that it not break anything, will try to use my terminal with `source /etc/profile`.

Thank you!

Please, give feedback, is it solved your situation?

**Comment by SturmB** [comment]
I had added `source /etc/profile.d/rubygems.sh` to my `~/.zshrc.local` file a few days ago and it appears to work.

Just now, I tried the second option and that, too, appears to work without issue. Perhaps this should somehow be added to this role? Perhaps included in `.zshrc`?

**Comment by popstas** [comment]
@SturmB , added variable `zsh_load_etc_profile` (default: yes) will load /etc/profile.d scripts, in `~/zshrc`. Thank you!
