### ISSUE TITLE
autosuggestions: Wishing to delete the Ctrl+U binding

### ISSUE THREAD

**Issue by ficapy** [viasite-ansible/ansible-role-zsh#50]
Thank you for your work, the results are fantastic. When I get a new machine I just run curl 
```
https://raw.githubusercontent.com/viasite-ansible/ansible-role-zsh/master/install.sh | bash
```
But the default setting I think has a drawback
```
bindkey '^U' autosuggest-accept
```
This is done by default with Ctrl+E, and the binding disables the original Ctrl+U.

It is proposed that it be deleted from the project

**Comment by popstas** [comment]
Agreed, I removed this hotkey from default [playbook.yml](https://github.com/viasite-ansible/ansible-role-zsh/blob/master/playbook.yml)
