### ISSUE TITLE
How to deal with autoload and oh-my-zsh plugins?

### ISSUE THREAD

**Issue by SturmB** [viasite-ansible/ansible-role-zsh#52]
Is it possible to have a program installed with this role that is only installed via `autoload`?

For example, I wish to have `zmv` installed, along with all the other extras (powerlevel10k, zsh-autosuggestions, etc.). However, I don't think I can simply add it to the `zsh_antigen_bundles_extras` variable because it's not considered a bundle. According to my research, it can only be installed by running `autoload zmv` on the shell. The same goes for another program called `zcalc`.

The same goes for enabling built-in oh-my-zsh plugins. I'd like to enable `npm` and `sudo`, but I don't know how to do it with this role, short of manually editing the `.zshrc.local` file _after_ running it.

Is there a way to install these things with this role instead?

**Comment by popstas** [comment]
@SturmB, now you can add any code in variable zsh_custom_before, zsh_custom_after.

- zsh_custom_before - before include antigen.zsh
- zsh_custom_after - before include ~/.zshrc.local
