### ISSUE TITLE
please remove zsh_reload

### ISSUE THREAD

**Issue by ficapy** [viasite-ansible/ansible-role-zsh#54]
When opened, it will prompt
```
The `zsh_reload` plugin is deprecated and will be removed.
Use `omz reload` or `exec zsh` instead.
```
omz includes this function, so the zsh_reload plugin is not needed

**Comment by popstas** [comment]
@ficapy, done!

**Comment by hernanmd** [comment]
Could you comment how did you removed the zsh_reload plugin?
Should one use zinit for example?

**Comment by popstas** [comment]
See commit - https://github.com/viasite-ansible/ansible-role-zsh/commit/eccf63b76095f486c24129fa6df11fb557efbe6c

I removed zsh_reload from bundle list.
