### ISSUE TITLE
http://ppa.launchpad.net/morphis/anbox-support/ubuntu focal Release   404  Not Found

### ISSUE THREAD

**Issue by fessnt** [viasite-ansible/ansible-role-zsh#55]
# Zero-knowledge install doesn't match correct behavior

## Current behavior:
![Снимок экрана от 2021-11-04 22-59-22](https://user-images.githubusercontent.com/92755876/140394512-2ec209b1-8c18-46ab-aceb-ca23b11989a9.png)
![Снимок экрана от 2021-11-04 22-59-37](https://user-images.githubusercontent.com/92755876/140394517-90e81adf-bb14-403c-bac5-6d569805cfda.png)
![Снимок экрана от 2021-11-04 23-01-16](https://user-images.githubusercontent.com/92755876/140394519-08875da4-1a6b-4cd4-abc0-a86d89cc9d47.png)

## Correct behavior:
1. User enters zero-knowledge code into terminal
2. Zero-knowledge installation
3. User happy

**Comment by popstas** [comment]
Just successfully installed on fresh Ubuntu 20.04.3

@fessnt, @vvmspace, ansible-role-zsh don't install `ppa:morphis/anbox-support` that causes error.
Try to remove this repository:

```
sudo add-apt-repository --remove ppa:morphis/anbox-support
```

And try zero install again.
