### ISSUE TITLE
TASK [viasite-ansible.zsh : Install zsh, git, wget, fd-find] failed on Mac 13.6.4

### ISSUE THREAD

**Issue by Bussmeyer** [viasite-ansible/ansible-role-zsh#76]
I am on a 

Mac Intel on Ventura 13.6.4

My playbook looks like:

```
---
- name: Configure host
  hosts: all

  roles:
    - role: viasite-ansible.zsh
      tags: ['zsh']
```

If I run 
`ansible-playbook main.yml -K --tags="zsh"`

I get the following error message:

```
TASK [viasite-ansible.zsh : Install zsh, git, wget, fd-find] ***********************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Error: Running Homebrew as root is extremely dangerous and no longer supported.\nAs Homebrew does not drop privileges on installation you would be giving all\nbuild scripts full access to your system."}
```

If I change in install.yml to `become: no` in line 18, the next error pops up.

```
TASK [viasite-ansible.zsh : Install zsh, git, wget, fd-find] ************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Error: No available formula with the name \"fd-find\". Did you mean ffind?"}
```

fd-find is not available via brew on Mac.

If I change the line 15 in install.yml to `- fd` everthing works fine. As `fd` is available via brew.

**Comment by popstas** [comment]
Hello, tried to fix it.

**Comment by Bussmeyer** [comment]
Hey @popstas, thanks for the fix. I can confirm that it fixes the second error I mentioned. The first one still pops up.

`TASK [viasite-ansible.zsh : Install zsh, git, wget, fd-find] ***********************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Error: Running Homebrew as root is extremely dangerous and no longer supported.\nAs Homebrew does not drop privileges on installation you would be giving all\nbuild scripts full access to your system."}
`

**Comment by popstas** [comment]
Thank you, I'm going to obtain a MacOS machine in June and investigate how to fix it.

**Comment by popstas** [comment]
Hello, @Bussmeyer, i've made some changes for macos:
- Created [install-macos.sh](https://github.com/viasite-ansible/ansible-role-zsh/blob/master/install-macos.sh) script, added to [readme](https://github.com/viasite-ansible/ansible-role-zsh/tree/master?tab=readme-ov-file#macos-zero-knowledge-install)
- Fixed permissions issues
- Fixed some hotkeys

Can you try it?

**Comment by Bussmeyer** [comment]
Nice. It just works for me now :-)
