### ISSUE TITLE
Add MIT License in toplevel repository

### ISSUE THREAD

**Issue by reimarstier** [viasite-ansible/ansible-role-zsh#77]
Hey, I've been using your ansible role for quite some time and I'm very happy how it works. I noticed that it is mentioned to be MIT licensed in the galaxy meta file. Would you mind making this more obvious and add the MIT license in the toplevel of the git repo so GitHub shows this more prominently? This is the only thing keeping me from recommending your role wholeheartedly. Thanks!

**Comment by popstas** [comment]
Hello, sure, just added LICENSE file, thanks for advise!
